//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webbanhang
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACH_HANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACH_HANG()
        {
            this.CHUNG_TU_BAN = new HashSet<CHUNG_TU_BAN>();
            this.CHUNG_TU_MUA = new HashSet<CHUNG_TU_MUA>();
        }
    
        public int ID_KHACH_HANG { get; set; }
        public string TEN_KH { get; set; }
        public string DIACHI { get; set; }
        public string SODIENTHOAI { get; set; }
        public byte[] HINHANH { get; set; }
        public Nullable<bool> SOB { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHUNG_TU_BAN> CHUNG_TU_BAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHUNG_TU_MUA> CHUNG_TU_MUA { get; set; }
    }
}
