//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webbanhang
{
    using System;
    using System.Collections.Generic;
    
    public partial class KY_THONG_KE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KY_THONG_KE()
        {
            this.CHUNG_TU_BAN = new HashSet<CHUNG_TU_BAN>();
            this.CHUNG_TU_MUA = new HashSet<CHUNG_TU_MUA>();
        }
    
        public int ID_THONGKE { get; set; }
        public Nullable<System.DateTime> NGAYBATDAU { get; set; }
        public Nullable<System.DateTime> NGAYKETHUC { get; set; }
        public string TENTHONGKE { get; set; }
        public Nullable<int> SONGAYHOATDONG { get; set; }
        public Nullable<decimal> TONGDOANHTHU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHUNG_TU_BAN> CHUNG_TU_BAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHUNG_TU_MUA> CHUNG_TU_MUA { get; set; }
    }
}
