//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webbanhang
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public string TenTaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public string LoaiTK { get; set; }
        public int ID_TK { get; set; }
        public int ID_NHAN_VIEN { get; set; }
    
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
    }
}
