//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webbanhang
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_DMHANGHOA
    {
        public int ID_HANGHOA { get; set; }
        public string TENHANGHOA { get; set; }
        public string DONVITINH { get; set; }
        public Nullable<decimal> GIATRI { get; set; }
        public string TENPHANLOAI { get; set; }
    }
}
